name: Rubber-stamp
on: pull_request_target

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Rubber-stamp
        if: github.actor == 'dependabot[bot]' || github.actor == 'jsoref'
        run: >-
          (
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            PR=${{ github.event.pull_request.number }}
            if
              !
              gh
              pr
              view $PR
              --json reviews
              -q '.reviews' |
              jq -r '.[] | select(.state=="APPROVED") | .state' |
              grep -q APPROVED
            ; then;
              gh pr review
              -R $GITHUB_REPOSITORY
              $PR
              --approve -b ':shrug:'
            fi
          )
